name: Create CalVer release

on:
  workflow_call:
    inputs:
      configuration:
        type: string
    outputs:
      version:
        description: "New version tag"
        value: ${{ jobs.create-release.outputs.version }}
      changelog:
        description: "Changelog contents"
        value: ${{ jobs.create-release.outputs.changelog }}

jobs:
  create-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: read
    outputs:
      version: ${{ steps.bump-calver.outputs.new_version }}
      changelog: ${{ steps.changelog.outputs.changelog }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get latest tag
        uses: WyriHaximus/github-action-get-previous-tag@v1
        id: get-latest-tag
        with:
          fallback: 23.01.0

      - name: Bump version
        uses: juusopiikkila/action-bump-calver@main
        id: bump-calver
        with:
          current_version: ${{ steps.get-latest-tag.outputs.tag }}

      - name: Push tag
        uses: thejeff77/action-push-tag@v1.0.0
        with:
          tag: ${{ steps.bump-calver.outputs.new_version }}
          message: "${{ steps.bump-calver.outputs.new_version }}"

      - name: Build changelog
        id: changelog
        uses: mikepenz/release-changelog-builder-action@v5
        with:
          fromTag: ${{ steps.get-latest-tag.outputs.tag }}
          toTag: ${{ steps.bump-calver.outputs.new_version }}
          configuration: ${{ inputs.configuration }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.bump-calver.outputs.new_version }}
          name: ${{ steps.bump-calver.outputs.new_version }}
          body: ${{ steps.changelog.outputs.changelog }}
          token: ${{ secrets.GITHUB_TOKEN }}
