name: Prune containers

description: Prune *un-tagged* versions of a GHCR package

on:
  workflow_call:
    inputs:
      container:
        type: string
        required: true
        description: "Container name without organization"
      older-than:
        type: number
        default: 7
        description: "Prune containers older than X days"
      keep-last:
        type: number
        default: 5
        description: "Keep last X un-tagged versions"
      
    secrets:
      token:
        required: true
        description: "Private access token with packages read/delete permission"

jobs:
  prune:
    runs-on: ubuntu-latest
    steps:
      - name: Container cleanup
        uses: dataaxiom/ghcr-cleanup-action@v1
        with:
          token: ${{ secrets.TOKEN }}
          owner: meikooy
          package: ${{ inputs.container }}
          older-than: ${{ inputs.older-than }} days
          keep-n-untagged: ${{ inputs.keep-last }}
          
