name: Encode secrets

on:
  workflow_call:
    inputs:
      content:
        type: string
        required: true
     outputs:
      value:
        description: "Encoded contents"
        value: ${{ steps.encode.outputs.content }}

jobs:
  handle:
    runs-on: ubuntu-latest
    steps:
      - run: echo '::set-output name=content::$(echo ${{ inputs.content }} | base64 |  sed 's/./&./g')'
        id: encode
